config/routes.rb
Rails.application.routes.draw do

  root 'oinks#index'

  resources :oinks, except: %w(edit new update)

  resources :analytics, except: %w(create edit new update show)
end

app/models/analytics.rb
require 'cassandra'
require 'time'

# Oink class that talks to Cassandra
class Analytics
  @@cluster = Cassandra.cluster(
    hosts: ['cassandra-dcos-node.cassandra.dcos.mesos'])
  @@keyspace = 'oinker'
  @@session  = @@cluster.connect(@@keyspace)
  @@paging_state = nil

  attr_accessor :key, :frequency

  def self.all(paged = false)
    results = @@session.execute(
      'SELECT key, frequency FROM analytics ' \
      'WHERE kind = ? ORDER BY frequency DESC',
      arguments: ['oink'],
      page_size: 25,
      paging_state: (paged ? @@paging_state : nil)
    )
    @@paging_state = results.paging_state
    results.map do |anal|
      c = Analytics.new
      c.key, c.frequency = anal['key'], anal['frequency']
      c
    end
  end
end

app/models/oink.rb
require 'cassandra'
require 'time'

# Oink class that talks to Cassandra
class Oink
  @@cluster = Cassandra.cluster(
    hosts: ['cassandra-dcos-node.cassandra.dcos.mesos'])
  @@keyspace = 'oinker'
  @@session  = @@cluster.connect(@@keyspace)
  @@generator = Cassandra::Uuid::Generator.new
  @@paging_state = nil

  attr_accessor :id, :content, :created_at, :handle

  attr_writer :content, :created_at, :handle

  def avatar_url
    "//robohash.org/#{handle}.png?size=144x144&amp;bgset=bg2"
  end

  def destroy
    @@session.execute(
      'DELETE from oinks WHERE id = ?',
      arguments: [@id])
  end

  def self.all(paged = false)
    result = @@session.execute(
      'SELECT id, content, created_at, handle FROM oinks ' \
      'WHERE kind = ? ORDER BY created_at DESC',
      arguments: ['oink'],
      page_size: 25,
      paging_state: (paged ? @@paging_state : nil)
    )
    @@paging_state = result.paging_state
    result.map do |oink|
      c = Oink.new
      c.id, c.content, c.handle = oink['id'], oink['content'], oink['handle']
      c.created_at = oink['created_at'].to_time.utc.iso8601
      c
    end
  end

  def self.create(params)
    c = Oink.new
    c.id = SecureRandom.urlsafe_base64
    c.content = params[:content]
    cassandra_time = @@generator.now
    c.created_at = cassandra_time.to_time.utc.iso8601
    c.handle = params[:handle].downcase
    @@session.execute(
      'INSERT INTO oinks (kind, id, content, created_at, handle) ' \
      'VALUES (?, ?, ?, ?, ?)',
      arguments: ['oink', c.id, c.content, cassandra_time, c.handle])
    c
  end

  def self.find(id)
    oink = @@session.execute(
      'SELECT id, content, created_at, handle FROM oinks WHERE id = ?',
      arguments: [id]).first
    c = Oink.new
    c.id = oink['id']
    c.content = oink['content']
    c.created_at = oink['created_at'].to_time.utc.iso8601
    c.handle = oink['handle']
    c
  end
end

app/controllers/analytics_controller.rb
# Analytics coontroller
class AnalyticsController < ActionController::Base
  layout 'application'

  def index
    @analytics = Analytics.all
  end
end

app/controllers/application_controller.rb
# Main application controller
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/oinks_controller.rb
# Oinks coontroller
class OinksController < ActionController::Base
  layout 'application'

  def create
    Oink.create(oink_params)
    redirect_to root_path
  end

  def destroy
    Oink.find(params[:id]).destroy
    redirect_to root_path
  end

  def index
    @oinks = Oink.all(params[:paged].present?)
  end

  def show
    @oink = Oink.find(params[:id])
  end

  private

  def oink_params
    params.require(:oink).permit(:content, :handle)
  end
end

app/views/analytics/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="list-group">
        <% if @analytics.length < 1 %>
          <h3 class="text-muted text-center">
            You haven't done any analyzing, or you have no oinks to analyze!
          </h3>
        <% else %>
          <% @analytics.each do |anal| %>
            <div class="list-group-item">
              <span class="badge"><%= anal.frequency %></span>
              <h4><%= anal.key %></h4>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Oinker</title>
    <link rel="icon" type="image/png" href="<%= image_path('oinker.png') %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <a class="navbar-brand" href="/">
          <img height="22" width="22" src="<%= image_path('oinker.png') %>" alt="" style="vertical-align: top;">
          Oinker
        </a>
        <ul class="nav navbar-nav">
          <li><a href="/analytics" style="margin-top: 5px; margin-bottom: 5px; padding-top: 10px; padding-bottom: 6px;">Analytics</a></li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/oinks/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= form_tag("/oinks", :method => "post") do |form| %>
            <div class="form-group">
              <%= label_tag "oink[handle]", "Handle" %>
              <%= text_field_tag "oink[handle]", nil,
                :autofocus => true,
                :class => "form-control",
                :maxlength => 15,
                :required => true,
                :pattern => "^[\\S]*$",
                :title => "Handles cannot contain spaces" %>
            </div>
            <div class="form-group">
              <%= label_tag "oink[content]", "Compose new Oink" %>
              <%= text_area_tag "oink[content]", nil,
                :class => "form-control",
                :maxlength => 140,
                :required => true,
                :style => "resize: vertical;" %>
            </div>
            <div class="form-group clearfix">
              <%= submit_tag("Oink", :class => "btn btn-primary btn-sm pull-right") %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="list-group">
        <% if @oinks.length < 1 %>
          <h3 class="text-muted text-center">
            What are you waiting for?<br>Start oinking.
          </h3>
        <% else %>
          <% @oinks.each do |oink| %>
            <div class="list-group-item">
              <div class="media">
                <div class="pull-left">
                  <img class="img-rounded media-object" src="<%= oink.avatar_url %>"
                    width="48" height="48" alt="<%= oink.handle %>">
                </div>
                <div class="media-body">
                  <h5 class="media-heading">
                    <div class="pull-right">
                      <%= form_tag(oink_path(oink.id), :method => "delete") do |form| %>
                        <%= hidden_field("oink[id]", oink.id) %>
                        <!-- <%= submit_tag("X", :class => "btn btn-link btn-xs text-muted", :title => "Delete oink") %> -->
                      <% end %>
                    </div>
                    @<%= oink.handle %> &middot;
                    <!-- <a href="<%= oink_path(oink.id) %>"> -->
                      <small>
                        <% created_at = oink.created_at %>
                        <time datetime="<%= created_at %>">
                          <%= time_ago_in_words(DateTime.parse(created_at)) %>
                        </time>
                      </small>
                    <!-- </a> -->
                  </h5>
                  <%= simple_format oink.content, :class => "oink-content" %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/oinks/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="list-group">
          <div class="list-group-item">
            <div class="media">
              <div class="pull-left">
                <img class="img-rounded media-object" src="<%= @oink.avatar_url %>"
                  width="48" height="48" alt="<%= @oink.handle %>">
              </div>
              <div class="media-body">
                <h5 class="media-heading">
                  <div class="pull-right">
                    <%= form_tag(oink_path(@oink.id), :method => "delete") do |form| %>
                      <%= hidden_field("oink[id]", @oink.id) %>
                      <%= submit_tag("X", :class => "btn btn-link btn-xs text-muted", :title => "Delete oink") %>
                    <% end %>
                  </div>
                  @<%= @oink.handle %>
                </h5>
                <%= simple_format @oink.content, :class => "oink-content lead" %>
              </div>
              <hr>
              <div class="text-muted">
                <% created_at = @oink.created_at %>
                <time datetime="<%= created_at %>">
                  <%= DateTime.parse(created_at).strftime("%H:%M UTC - %d %b %Y") %>
                </time>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>